services:
  nginx:
    image: nginx:1.24
    ports:
      - '8000:80'
      - '8001:8001'
    volumes:
      - ./laravel:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    restart: always
  php-fpm:
    build: ./docker/php-fpm
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./laravel:/var/www/html
      - ./docker/php-fpm/docker-php-ext-opcache.ini:/usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
      - ./docker/php-fpm/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php-fpm/php.ini:/usr/local/etc/php/conf.d/zzmyphp.ini
      - ./docker/php-fpm/php-fpm.conf:/usr/local/etc/php-fpm.d/zzmyphp-fpm.conf
    restart: always
    command: strace -f -s 1024 -o /var/www/html/storage/logs/trace.txt php-fpm
    depends_on:
      - db
      - db-test
  db: &db
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=app
      - LC_ALL=C
  db-test:
    *db
